[project]
name = "pyutils"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14.2"
dependencies = [
    "alphashape>=1.3.1",
    "geopandas>=1.1.1",
    "pandas>=2.3.3",
    "requests>=2.32.5",
]

[tool.uv.workspace]
members = [
    "test",
]
